### ISSUE TITLE
Warning while trying to save images in redux store

### ISSUE THREAD

**Issue by loorely** [FundacionParaguaya/stoplight-mobile#1212]
** Problem ** 

We are getting a warning/error everytime we try to upload and image: 

`ExceptionsManager.js:82 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Location (created by Connect(Location))
    in Connect(Location) (created by NamespacesConsumerComponent)
    in NamespacesConsumerComponent (created by WithMergedOptions)
    in WithMergedOptions (created by Context.Consumer)
    in WithMergedOptions(NamespacesConsumerComponent) (created by LoadNamespace)
    in LoadNamespace (created by WithMergedOptions)
    in WithMergedOptions (created by Context.Consumer)
    in LoadNamespace(Connect(Location)) (at SceneView.js:9)
    in SceneView (at StackViewLayout.tsx:899)
    in RCTView (at View.js:45)
    in View (at StackViewLayout.tsx:898)
    in RCTView (at View.js:45)
    in View (at StackViewLayout.tsx:897)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewCard.tsx:106)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:101)
    in Screen (at StackViewCard.tsx:93)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:982)`

![image.png](https://images.zenhubusercontent.com/5907a75d51aa2c30577cf78c/8a9acf25-654d-4966-8f50-8beb25b67691)

**Comment by zommerberg** [comment]
# Problem
The problem occurs due to unnecessary mounting of the side navbar component. This happens ONLY when we get the second permission request to use the camera. The first time we get the "write on the device " request, this causes the side nav bar to open. Then after we accept it closes and it opens again when the second request to use the camera comes in. 
This has no effect on the user and happens only once. It indicates that the side navbar could not close fast enough because we try to immediately open it again.  It has nothing to do with redux-store and memory leaks. 

# Solution
The solution would be to identify the reason the side nav bar is opening.

**Comment by zommerberg** [comment]
I have investigated the issue much more and it appears we dont completely unmount  the locations screen. This warning is simply telling us that the location screen is still mounted and we are opening the pictures screen.  This is a navigation warning that is not seen by the user and does not cause crashes and is not linked with redux or memory problems. I propose to leave it for the react-native update we will do in the future. The whole update will include navigation changes and this problem will disappear by itself.
